[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fiware-mcp-client"
version = "0.1.0"
description = "FIWARE MCP client utilities and CLI"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [
    { name = "Alvaro Max" }
]
dependencies = [
    "fastapi",
    "openai",
    "openai-agents",
    "python-dotenv",
    "pydantic",
    "PyYAML",
    "requests>=2.31.0",
    "gradio",
    "uvicorn",
    "fastmcp>=0.3.0",
    "mcp[cli]",
    "haversine"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-mock"
]

[tool.setuptools.packages.find]
include = ["app*"]
